version: "3.9"

services:
  server:
    build: ./server
    container_name: server
    env_file:
      - ./.env.docker
    restart: always

  bot:
    build: ./bot
    container_name: bot
    depends_on:
      - server
    restart: always
    env_file:
      - ./.env.docker